apiVersion: v1
kind: Namespace
metadata:
  name: flow-server-grpc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-server-deployment
  namespace: flow-server-grpc
  labels:
    app: flow-server
spec:
  selector:
    matchLabels:
      app: flow-server
  replicas: 1
  template:
    metadata:
      labels:
        app: flow-server
    spec:
      containers:
        - name: flow-server
          image: flow-server:latest
          imagePullPolicy: Never
          ports:
            - name: fs-service
              containerPort: 50052

---
apiVersion: v1
kind: Service
metadata:
  name: fs-service
  namespace: flow-server-grpc
spec:
  selector:
    app: flow-server
  ports:
    - port: 50052
      targetPort: fs-service