apiVersion: v1
kind: Namespace
metadata:
  name: processing-container

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-container-deployment
  namespace: processing-container
  labels:
    app: processing-container
spec:
  selector:
    matchLabels:
      app: processing-container
  replicas: 1
  template:
    metadata:
      labels:
        app: processing-container
    spec:
      containers:
        - name: processing-container
          image: processing-container:latest
          imagePullPolicy: Never
          ports:
            - name: pc-service
              containerPort: 50055

---
apiVersion: v1
kind: Service
metadata:
  name: pc-service
  namespace: processing-container
spec:
  selector:
    app: processing-container
  ports:
    - port: 50055
      targetPort: pc-service