apiVersion: v1
kind: Namespace
metadata:
  name: smooth-server-grpc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smooth-server-deployment
  namespace: smooth-server-grpc
spec:
  selector:
    matchLabels:
      app: smooth-server
  template:
    metadata:
      labels:
        app: smooth-server
    spec:
      containers:
      - name: smooth-server-container
        image: smooth-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50054
        env:
        - name: APP_PORT
          value: "50054"
        livenessProbe:
          grpc:
            port: 50054
          initialDelaySeconds: 10
          periodSeconds: 10
        # readinessProbe:
        #   grpc:
        #     port: 50054
        #   initialDelaySeconds: 10
        #   periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: smooth-server-service
  namespace: smooth-server-grpc
spec:
  selector:
    app: smooth-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50054
      targetPort: 50054