apiVersion: v1
kind: Namespace
metadata:
  name: stabilize-server-grpc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stabilize-server-deployment
  namespace: stabilize-server-grpc
spec:
  selector:
    matchLabels:
      app: stabilize-server
  template:
    metadata:
      labels:
        app: stabilize-server
    spec:
      containers:
      - name: stabilize-server-container
        image: stabilize-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        env:
        - name: APP_PORT
          value: "50051"
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 10
        # readinessProbe:
        #   grpc:
        #     port: 50051
        #   initialDelaySeconds: 10
        #   periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: stabilize-server-service
  namespace: stabilize-server-grpc
spec:
  selector:
    app: stabilize-server
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051